Repository Zoo-Money/ZooMoney_BackEnd, pull requests merged in 2025-03, with the labels that each got.

#7 [fix] 테이블 관련 Entity 수정
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/card/ChildCardEntity.java
  src/main/java/com/shinhan/zoomoney/card/ChildCardRepositiory.java
  src/main/java/com/shinhan/zoomoney/card/UseHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/child/ChildEntity.java
  src/main/java/com/shinhan/zoomoney/child/NotifyEntity.java
  src/main/java/com/shinhan/zoomoney/daily/DailyEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/PlanDetailEntity.java
  src/main/java/com/shinhan/zoomoney/parent/ContractEntity.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultEntity.java
Labels: fix, 김용범

#8 [Feat]: 뉴스 검색 api 연동 (#1)
  gradlew
  src/main/java/com/shinhan/zoomoney/CorsConfig.java
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/card/ChildCardEntity.java
  src/main/java/com/shinhan/zoomoney/card/ChildCardRepositiory.java
  src/main/java/com/shinhan/zoomoney/card/UseHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/child/ChildEntity.java
  src/main/java/com/shinhan/zoomoney/child/NotifyEntity.java
  src/main/java/com/shinhan/zoomoney/daily/DailyEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/PlanDetailEntity.java
  src/main/java/com/shinhan/zoomoney/parent/ContractEntity.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsController.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsService.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultEntity.java
Labels: feat, 정재윤

#13 [feat]: 주식 info 개발(#11)
  src/main/java/com/shinhan/zoomoney/stock/StockInfoController.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoService.java
Labels: feat, 박은수

#17 [fix]:Entity 카멜표기법 수정(#16)
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/card/ChildCardEntity.java
  src/main/java/com/shinhan/zoomoney/card/UseHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/child/ChildEntity.java
  src/main/java/com/shinhan/zoomoney/child/NotifyEntity.java
  src/main/java/com/shinhan/zoomoney/daily/DailyEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/CategoryEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/PlanDetailEntity.java
  src/main/java/com/shinhan/zoomoney/parent/ContractEntity.java
  src/main/java/com/shinhan/zoomoney/parent/ParentEntity.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryBackupEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockMoneyEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultEntity.java
Labels: fix, 김용범

#20 [fix]:자녀 관련된 Entity 수정(#19)
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/card/CardDto.java
  src/main/java/com/shinhan/zoomoney/card/CardEntity.java
  src/main/java/com/shinhan/zoomoney/card/CardRepositiory.java
  src/main/java/com/shinhan/zoomoney/card/CardService.java
  src/main/java/com/shinhan/zoomoney/card/UseHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/child/ChildDto.java
  src/main/java/com/shinhan/zoomoney/child/ChildEntity.java
  src/main/java/com/shinhan/zoomoney/daily/DailyEntity.java
  src/main/java/com/shinhan/zoomoney/member/MemberEntity.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanEntity.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyEntity.java
  src/main/java/com/shinhan/zoomoney/parent/ContractEntity.java
  src/main/java/com/shinhan/zoomoney/parent/ParentDto.java
  src/main/java/com/shinhan/zoomoney/parent/ParentEntity.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryBackupEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockMoneyEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultEntity.java
Labels: fix, 김용범

#21 [fix]: 불필요한 파일 정리 및 트리 수정
  src/main/java/com/shinhan/zoomoney/notify/NotifyRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartController.java
Labels: fix, 전운종

#24 [fix]: 알림 코드 수정
  src/main/java/com/shinhan/zoomoney/AppConfig.java
  src/main/java/com/shinhan/zoomoney/CorsConfig.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyRepository.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyService.java
Labels: fix, 전운종

#25 [feat]:로그인/로그아웃 API 개발(#15)
  src/main/java/com/shinhan/zoomoney/member/MemberController.java
  src/main/java/com/shinhan/zoomoney/member/MemberEntity.java
  src/main/java/com/shinhan/zoomoney/member/MemberRepository.java
  src/main/java/com/shinhan/zoomoney/member/MemberService.java
Labels: feat, 김용범

#26 [feat]: 주식 info 개발(#11)
  build.gradle
  src/main/java/com/shinhan/zoomoney/stock/StockInfoController.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoDto.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoService.java
Labels: feat, 박은수

#29 [feat]: 회원정보 조회 api 개발(#28)
  src/main/java/com/shinhan/zoomoney/member/MemberController.java
  src/main/java/com/shinhan/zoomoney/member/MemberRepository.java
  src/main/java/com/shinhan/zoomoney/member/MemberService.java
Labels: ✅ feat, 박은수

#33 [feat]:회원이등록된 카드정보 API 및 파일 네이밍변경(#30)
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/card/CardRepositiory.java
  src/main/java/com/shinhan/zoomoney/card/CardRepository.java
  src/main/java/com/shinhan/zoomoney/card/CardService.java
Labels: ✅ feat, 김용범

#35 [Fix] 뉴스 검색 api 수정 (#10)
  build.gradle
  src/main/java/com/shinhan/zoomoney/stock/StockNewsController.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsService.java
Labels: 🛠️ fix, 정재윤

#36 [feat]: 저금통 생성 기능 추가 (#12)
  build.gradle
  src/main/java/com/shinhan/zoomoney/account/AccountController.java
  src/main/java/com/shinhan/zoomoney/account/AccountDto.java
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/account/AccountRepository.java
  src/main/java/com/shinhan/zoomoney/account/AccountService.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyController.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyDto.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyRepository.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyService.java
Labels: ✅ feat, 전운종

#40 [fix]:누락파일생성 및 수정(#39)
  build.gradle
  src/main/java/com/shinhan/zoomoney/stock/StockNewsController.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsService.java
Labels: 🛠️ fix, 정재윤

#43 [feat]:카드 발급(등록)API 개발 및 UseHistoryEntity /CardEntity 수정(#31)
  src/main/java/com/shinhan/zoomoney/CorsConfig.java
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/card/CardEntity.java
  src/main/java/com/shinhan/zoomoney/card/CardRepository.java
  src/main/java/com/shinhan/zoomoney/card/CardService.java
  src/main/java/com/shinhan/zoomoney/card/UseHistoryEntity.java
  src/main/java/com/shinhan/zoomoney/member/MemberRepository.java
Labels: ✅ feat, 김용범

#45 [feat]: 금융 퀴즈 ai 연동 개발 (#3)
  src/main/java/com/shinhan/zoomoney/notify/NotifyService.java
  src/main/java/com/shinhan/zoomoney/quiz/KeywordController.java
  src/main/java/com/shinhan/zoomoney/quiz/KeywordDto.java
  src/main/java/com/shinhan/zoomoney/quiz/KeywordEntity.java
  src/main/java/com/shinhan/zoomoney/quiz/KeywordRepository.java
  src/main/java/com/shinhan/zoomoney/quiz/KeywordService.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizController.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizDto.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizEntity.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizRepository.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizResponseDto.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizService.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizSubmitDto.java
  src/main/java/com/shinhan/zoomoney/quiz/RestTemplateConfig.java
Labels: ✅ feat, 강은영

#48 [feat]: 종목 상세 페이지 회사정보 크롤링(#42)
  build.gradle
  src/main/java/com/shinhan/zoomoney/stock/CompanyInfoService.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartController.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartService.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartTokenService.java
  src/main/java/com/shinhan/zoomoney/stock/StockDto.java
Labels: ✅ feat, 정홍택

#50 [feat]: 저금통 기능 개발 (#12)
  src/main/java/com/shinhan/zoomoney/account/AccountController.java
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/account/AccountRepository.java
  src/main/java/com/shinhan/zoomoney/account/AccountService.java
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/card/CardService.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyRepository.java
Labels: ✅ feat, 전운종

#51 [feat]: 거래내역 조회 api 개발(#44)
  src/main/java/com/shinhan/zoomoney/card/UseHistoryRepositiory.java
  src/main/java/com/shinhan/zoomoney/card/UseHistoryService.java
Labels: ✅ feat, 박은수

#52 [fix]: 모의투자종목 상세페이지 회사설명 기능 수정 /#49
  src/main/java/com/shinhan/zoomoney/stock/StockChartController.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartService.java
Labels: 🛠️ fix, 정홍택

#54 [feat] : 출석체크 기능 개발 (#47)
  src/main/java/com/shinhan/zoomoney/daily/DailyController.java
  src/main/java/com/shinhan/zoomoney/daily/DailyRepository.java
  src/main/java/com/shinhan/zoomoney/daily/DailyService.java
Labels: ✅ feat, 강은영

#55 [Feat]:용돈계획기능(#41)
  src/main/java/com/shinhan/zoomoney/moneyplan/CategoryRepository.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanContractRepository.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanController.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanDto.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanRepository.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanService.java
  src/main/java/com/shinhan/zoomoney/moneyplan/PlanDetailRepository.java
  src/main/java/com/shinhan/zoomoney/moneyplan/PlanDetailService.java
Labels: ✅ feat, 정재윤

#56 [feat]: 카드 이미지 변경 API 개발
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/card/CardEntity.java
  src/main/java/com/shinhan/zoomoney/card/CardRepository.java
  src/main/java/com/shinhan/zoomoney/card/CardService.java
  src/main/java/com/shinhan/zoomoney/member/MemberService.java
Labels: ✅ feat, 김용범

#58 [fix]:money plan repository 수정(#57)
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanContractRepository.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanService.java
Labels: 🛠️ fix, 정재윤

#60 [Fix]:뉴스검색기능수정(#59)
  build.gradle
  src/main/java/com/shinhan/zoomoney/stock/StockNewsController.java
Labels: 🛠️ fix, 정재윤

#64 [fix]:로그인controller 수정(#62)
  src/main/java/com/shinhan/zoomoney/member/MemberController.java
Labels: 🛠️ fix, 정재윤

#65 [feat]: 저금통 기능 개발 (#12)
  src/main/java/com/shinhan/zoomoney/account/AccountController.java
  src/main/java/com/shinhan/zoomoney/account/AccountDto.java
  src/main/java/com/shinhan/zoomoney/account/AccountEntity.java
  src/main/java/com/shinhan/zoomoney/account/AccountService.java
Labels: ✅ feat, 전운종

#67 [feat]: 금융 퀴즈 Main 개발 (#46)
  src/main/java/com/shinhan/zoomoney/quiz/QuizController.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizRepository.java
  src/main/java/com/shinhan/zoomoney/quiz/QuizService.java
Labels: ✅ feat, 강은영

#69 [feat]: 용돈계약서 api 개발(#2)
  .gitignore
  build.gradle
  src/main/java/com/shinhan/zoomoney/card/CardRepository.java
  src/main/java/com/shinhan/zoomoney/contract/ContractController.java
  src/main/java/com/shinhan/zoomoney/contract/ContractDto.java
  src/main/java/com/shinhan/zoomoney/contract/ContractEntity.java
  src/main/java/com/shinhan/zoomoney/contract/ContractRepository.java
  src/main/java/com/shinhan/zoomoney/contract/ContractService.java
  src/main/java/com/shinhan/zoomoney/contract/PdfService.java
  src/main/java/com/shinhan/zoomoney/contract/SignatureService.java
  src/main/java/com/shinhan/zoomoney/member/MemberController.java
  src/main/java/com/shinhan/zoomoney/member/MemberEntity.java
  src/main/java/com/shinhan/zoomoney/member/MemberRepository.java
  src/main/java/com/shinhan/zoomoney/member/MemberService.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsService.java
  src/main/resources/fonts/malgun.ttf
Labels: ✅ feat, 김은정

#72 [feat]: 전일 종가 api 연동(#66)
  src/main/java/com/shinhan/zoomoney/stock/StockClosingPrice.java
  src/main/java/com/shinhan/zoomoney/stock/StockEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockPriceController.java
  src/main/java/com/shinhan/zoomoney/stock/StockRepository.java
Labels: ✅ feat, 박은수

#74 [fix]: 불필요 코드 제거 및 포맷팅
  build.gradle
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/card/CardService.java
  src/main/java/com/shinhan/zoomoney/contract/ContractController.java
  src/main/java/com/shinhan/zoomoney/contract/ContractService.java
  src/main/java/com/shinhan/zoomoney/moneyplan/MoneyPlanController.java
  src/main/java/com/shinhan/zoomoney/stock/ApprovalKeyService.java
  src/main/java/com/shinhan/zoomoney/stock/CompanyInfoService.java
  src/main/java/com/shinhan/zoomoney/stock/MyWebSocketHandler.java
  src/main/java/com/shinhan/zoomoney/stock/RealTimePriceService.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartController.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartService.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartTokenService.java
  src/main/java/com/shinhan/zoomoney/stock/StockNewsService.java
Labels: 🛠️ fix, 전운종

#77 [fix]: 클라이언트 전달 data type 수정(#76)
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/member/MemberController.java
Labels: 🛠️ fix, 박은수

#79 [fix] Card 관련 API 수정(#73)
  src/main/java/com/shinhan/zoomoney/card/CardController.java
Labels: 🛠️ fix, 김용범

#83 [fix] stockPrice, stockhisPrice OwnedDto에 추가완료 /#81
  src/main/java/com/shinhan/zoomoney/stock/OwnedStockDto.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockService.java
Labels: 🛠️ fix, 정홍택

#84 [fix]: 알림 기능 CORS 설정 추가
  src/main/java/com/shinhan/zoomoney/card/CardController.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyController.java
  src/main/java/com/shinhan/zoomoney/stock/StockChartController.java
Labels: 🛠️ fix, 전운종

#88 [Feat]:모의 투자 거래 내역 조회 기능 생성 (#61)
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryController.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryDto.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryService.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultController.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultDto.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockResultService.java
Labels: ✅ feat, 정재윤

#93 [feat]: 모의 주식 참가 여부 확인(#82)
  src/main/java/com/shinhan/zoomoney/stock/StockController.java
  src/main/java/com/shinhan/zoomoney/stock/StockMoneyDto.java
  src/main/java/com/shinhan/zoomoney/stock/StockMoneyEntity.java
  src/main/java/com/shinhan/zoomoney/stock/StockMoneyRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockMoneyService.java
Labels: ✅ feat, 박은수

#94 [fix]: CardController 수정 (#91)
  src/main/java/com/shinhan/zoomoney/card/CardController.java
Labels: 🛠️ fix, 김용범

#97 [fix]: StockController owned 수정(#96)
  src/main/java/com/shinhan/zoomoney/stock/StockController.java
Labels: 🛠️ fix, 박은수

#99 [fix]: parameters 에러 해결(#98)
  src/main/java/com/shinhan/zoomoney/account/AccountController.java
  src/main/java/com/shinhan/zoomoney/account/AccountRepository.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyController.java
  src/main/java/com/shinhan/zoomoney/notify/NotifyRepository.java
Labels: 🛠️ fix, 정재윤

#100 [fix]: 알림 CORS 설정 제거
  src/main/java/com/shinhan/zoomoney/notify/NotifyController.java
Labels: 🛠️ fix, 전운종

#101 [fix]: stock userStatus 타입 수정, 코드 정리
  src/main/java/com/shinhan/zoomoney/stock/ApprovalKeyService.java
  src/main/java/com/shinhan/zoomoney/stock/MyWebSocketHandler.java
  src/main/java/com/shinhan/zoomoney/stock/RealTimePriceService.java
  src/main/java/com/shinhan/zoomoney/stock/StockController.java
  src/main/java/com/shinhan/zoomoney/stock/StockInfoController.java
Labels: 🛠️ fix, 박은수

#102 [fix]: 메인페이지 포인트 조회 api (#89)
  src/main/java/com/shinhan/zoomoney/member/MemberController.java
  src/main/java/com/shinhan/zoomoney/member/MemberRepository.java
  src/main/java/com/shinhan/zoomoney/member/MemberService.java
Labels: 🛠️ fix, 강은영

#106 [fix] 보유 주식 조회 기능 쿼리 수정 /#105
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryRepository.java
  src/main/java/com/shinhan/zoomoney/stock/StockService.java
Labels: 🛠️ fix, 정홍택

#107 [fix]: 출석체크 param으로 변경 (#103)
  src/main/java/com/shinhan/zoomoney/daily/DailyController.java
Labels: 🛠️ fix, 강은영

#109 [fix]: stockHistoryRepository 쿼리 수정(#108)
  src/main/java/com/shinhan/zoomoney/stock/StockController.java
  src/main/java/com/shinhan/zoomoney/stock/StockHistoryRepository.java
Labels: 🛠️ fix, 박은수

#115 [fix] : Member 카드정보 가져오기 API 수정 (#114)
  src/main/java/com/shinhan/zoomoney/card/controller/CardController.java
Labels: 🛠️ fix, 김용범

#117 [Fix]: 용돈 계획 memberNum 수정 (#113)
  src/main/java/com/shinhan/zoomoney/moneyplan/controller/MoneyPlanController.java
  src/main/java/com/shinhan/zoomoney/moneyplan/service/MoneyPlanService.java
  src/main/java/com/shinhan/zoomoney/stock/controller/StockInfoController.java
Labels: 🛠️ fix, 정재윤

#118 [fix]: 퀴즈 데이터 중복 삽입 방지 처리 (#111)
  src/main/java/com/shinhan/zoomoney/quiz/service/QuizService.java
Labels: 🛠️ fix, 강은영

#120 [feat] 종가 조회 기능 추가/#119
  src/main/java/com/shinhan/zoomoney/CorsConfig.java
  src/main/java/com/shinhan/zoomoney/stock/controller/StockChartController.java
  src/main/java/com/shinhan/zoomoney/stock/dto/StockDto.java
  src/main/java/com/shinhan/zoomoney/stock/service/StockChartService.java
Labels: ✅ feat, 정홍택

#121 [fix]: 불필요 import 제거
  src/main/java/com/shinhan/zoomoney/card/controller/CardController.java
Labels: 🛠️ fix, 전운종

#132 [fix]: gemini-api key annotaion 수정(130)
  src/main/java/com/shinhan/zoomoney/quiz/service/QuizService.java
Labels: 🛠️ fix, 강은영

#133 [fix] 평단가 기능 수정 /#190
  src/main/java/com/shinhan/zoomoney/stock/repository/StockHistoryRepository.java
  src/main/java/com/shinhan/zoomoney/stock/service/StockService.java
Labels: 🛠️ fix, 정홍택

#136 [Fix] 모의투자 2차 QA 수정 완료/#135
  src/main/java/com/shinhan/zoomoney/stock/repository/StockHistoryBackupRepository.java
  src/main/java/com/shinhan/zoomoney/stock/service/StockHistoryService.java
  src/main/java/com/shinhan/zoomoney/stock/service/StockService.java
Labels: 🛠️ fix, 정홍택

#137 [fix] 2차 피드백 수정/#135
  src/main/java/com/shinhan/zoomoney/stock/controller/StockHistoryController.java
  src/main/java/com/shinhan/zoomoney/stock/dto/StockHistoryBackupDto.java
  src/main/java/com/shinhan/zoomoney/stock/repository/StockHistoryBackupRepository.java
  src/main/java/com/shinhan/zoomoney/stock/service/StockHistoryService.java
Labels: 🛠️ fix, 정홍택

#138 [fix]:sort변경(#134)
  src/main/java/com/shinhan/zoomoney/moneyplan/repository/MoneyPlanRepository.java
  src/main/java/com/shinhan/zoomoney/moneyplan/service/MoneyPlanService.java
Labels: 🛠️ fix, 정재윤
